name: Helpers
on:
  workflow_run:
    workflows: ["Pull Request Tests"]
    types:
      - requested
env:
  app: Accept:application/vnd.github.v3+json
  base_url: $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs
  AUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pre:
    name: Preprocess
    runs-on: ubuntu-20.04

    steps:
    - name: Share helper id
      run: echo -n ${{ github.run_id }} >~/id_file

    - uses: actions/cache@v2
      with:
        path: ~/id_file
        key: helperid-${{ github.event.workflow_run.id }}

    - name: Delete run-ci label
      run: |
        head_sha=${{ github.event.workflow_run.head_sha }}
        url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY
        pr_number=$(curl -sS -H $app $url/pulls \
          | jq -r '.[] | select(.head.sha == "'"$head_sha"'") | .number')
        echo "pr_number is $pr_number"
        curl -sS -X DELETE -H $app -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          $url/issues/$pr_number/labels/run-ci


  repocheck:
    name: Repo check
    runs-on: ubuntu-20.04

    steps:
    - name: Check up-to-dateness and post comment
      run: |
        head_sha=${{ github.event.workflow_run.head_sha }}
        git clone -q ${{ github.event.workflow_run.head_repository.html_url }} .
        git checkout -q $head_sha
        git submodule -q update --init --recursive

        cd ${{ github.workspace }}/tests/ci
        url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY
        pr_number=${{ github.event.pull_request.number }}
